const TrustedContact = require('../models/TrustedContact');
const EmergencyAlert = require('../models/EmergencyAlert');
const CrisisEvent = require('../models/CrisisEvent');
const User = require('../models/User');
const sendEmail = require('../utils/emailService');

const hasSmsConfig = () => Boolean(
  process.env.SMS_ACCOUNT_SID &&
  process.env.SMS_AUTH_TOKEN &&
  process.env.SMS_FROM_NUMBER
);

const hasEmailConfig = () => Boolean(
  process.env.EMAIL_USERNAME && process.env.EMAIL_PASSWORD
);

function maskEmail(email) {
  const [localPart, domain] = email.split('@');
  if (!localPart || !domain) return 'invalid';
  return `${localPart.charAt(0)}***@${domain}`;
}

function formatPhone(phone) {
  const trimmed = phone.trim().replace(/[\s().-]/g, '');
  if (trimmed.startsWith('+')) return trimmed;
  if (/^[6-9]\d{9}$/.test(trimmed)) return `+91${trimmed}`;
  return `+${trimmed.replace(/\D/g, '')}`;
}

async function sendSms(to, body) {
  if (!hasSmsConfig()) return { status: 'not_configured' };

  try {
    const twilio = require('twilio');
    const client = twilio(process.env.SMS_ACCOUNT_SID, process.env.SMS_AUTH_TOKEN);
    const message = await client.messages.create({
      body,
      from: process.env.SMS_FROM_NUMBER,
      to: formatPhone(to)
    });
    console.log('SMS_STATUS: sent');
    console.log('SMS_MESSAGE_SID:', message.sid);
    return { status: 'sent', messageSid: message.sid };
  } catch (error) {
    console.log('SMS_STATUS: failed');
    console.log('SMS_ERROR_CODE:', error.code || 'unknown');
    console.log('SMS_ERROR_MESSAGE:', error.message || 'SMS delivery failed');
    return { status: 'failed', errorCode: error.code, errorMessage: error.message };
  }
}

async function sendEmergencyAlert({ userId, crisisEventId, trustedContact }) {
  const user = await User.findById(userId).select('firstName');
  if (!user) throw new Error('User not found for emergency alert');

  console.log('CRISIS_RISK: HIGH');
  console.log('TRUSTED_CONTACT: FOUND');
  console.log('TRUSTED_CONTACT_CONSENT:', trustedContact.emergencyAlertConsent);
  console.log('TRUSTED_CONTACT_EMAIL:', maskEmail(trustedContact.email));
  console.log('AUTH_USER: RESOLVED');

  const alert = await EmergencyAlert.create({
    user: userId,
    trustedContact: trustedContact._id,
    crisisEvent: crisisEventId,
    smsStatus: hasSmsConfig() ? 'pending' : 'not_configured',
    emailStatus: hasEmailConfig() ? 'pending' : 'not_configured'
  });

  const firstName = user.firstName || 'Someone';
  const smsBody = `MindfulSpace Emergency Support: ${firstName} may be experiencing a serious mental-health crisis and may need immediate support. Please check on them and contact them as soon as possible. This alert was generated by MindfulSpace.`;
  const emailText = `Hello ${trustedContact.name},\n\nMindfulSpace's safety system detected a high-risk crisis signal associated with ${firstName}'s account.\n\nThey may need immediate emotional support. Please check on them and contact them as soon as possible.\n\nIf you believe they are in immediate danger, encourage them to contact local emergency services or seek emergency medical help.\n\nThis message was generated by MindfulSpace's emergency support system.`;

  const [smsResult, emailResult] = await Promise.all([
    sendSms(trustedContact.phone, smsBody),
    hasEmailConfig()
      ? sendEmail({
        to: trustedContact.email,
        subject: 'MindfulSpace Emergency Support Alert',
        text: emailText
      }).then(result => ({
        status: result.success ? 'sent' : 'failed',
        errorCode: result.code,
        messageId: result.messageId
      }))
      : Promise.resolve({ status: 'not_configured' })
  ]);

  alert.smsStatus = smsResult.status;
  alert.smsErrorCode = smsResult.errorCode;
  alert.smsErrorMessage = smsResult.errorMessage;
  alert.emailStatus = emailResult.status;
  const deliveryStatus = emailResult.status === 'sent' || smsResult.status === 'sent'
    ? 'sent'
    : emailResult.status === 'not_configured' && smsResult.status === 'not_configured'
      ? 'not_configured'
      : 'failed';
  alert.deliveryStatus = deliveryStatus;
  if (smsResult.status === 'sent' || emailResult.status === 'sent') {
    alert.sentAt = new Date();
  }
  await alert.save();

  console.log('EMAIL_STATUS:', emailResult.status);
  if (emailResult.status === 'sent') {
    console.log('EMAIL_SEND_ATTEMPT: true');
    console.log('EMAIL_SMTP_ACCEPTED: true');
    console.log('EMAIL_MESSAGE_ID:', emailResult.messageId || 'unavailable');
  }
  if (emailResult.status === 'failed') console.log('EMAIL_ERROR_CODE:', emailResult.errorCode || 'delivery_failed');

  const deliveryConfirmed = smsResult.status === 'sent' || emailResult.status === 'sent';
  await CrisisEvent.findByIdAndUpdate(crisisEventId, {
    alert: alert._id,
    alertTriggered: deliveryConfirmed,
    status: deliveryConfirmed ? 'alert_sent' : 'alert_failed'
  });

  return {
    alertId: alert._id,
    smsStatus: smsResult.status,
    smsErrorCode: smsResult.errorCode,
    smsErrorMessage: smsResult.errorMessage,
    emailStatus: emailResult.status,
    emailMessageId: emailResult.messageId,
    deliveryConfirmed
  };
}

module.exports = {
  sendEmergencyAlert,
  sendSms,
  hasSmsConfig,
  hasEmailConfig,
  maskEmail
};
